# Generated by Django 5.2.1 on 2026-04-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_cobrar', '0002_remove_cuota_venta_alter_cuota_numero_credito_and_more'),
        ('cxc', '0003_producto_empresa_plazodetalle_productodetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito_compat', to='cxc.venta'),
        ),
        migrations.AlterModelTable(
            name='credito',
            table='cuentas_cobrar_credito',
        ),
        migrations.AlterModelTable(
            name='cuota',
            table='cuentas_cobrar_cuota',
        ),
    ]
