# Generated by Django 5.2.1 on 2026-04-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='venta',
            table='ventas_venta',
        ),
    ]
