# Generated by Django 5.2.1 on 2026-03-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'DEPOSITOS',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=5)),
                ('decimales', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'MONEDAS',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=5)),
                ('tipoid', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TIPOS_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo', models.CharField(max_length=100)),
                ('cuotas', models.PositiveIntegerField(default=1)),
                ('irregular', models.BooleanField(default=False)),
                ('tipo_documento', models.ForeignKey(db_column='tipoid', on_delete=django.db.models.deletion.PROTECT, to='cxc.tipodocumento')),
            ],
            options={
                'db_table': 'PLAZOS',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaproce', models.DateTimeField()),
                ('fechafactura', models.DateField()),
                ('serie', models.CharField(max_length=10)),
                ('nrofactura', models.PositiveIntegerField()),
                ('timbrado', models.CharField(blank=True, max_length=20)),
                ('timbrado_vence', models.DateField(blank=True, null=True)),
                ('totalexentas', models.PositiveBigIntegerField(default=0)),
                ('totalimponible', models.PositiveBigIntegerField(default=0)),
                ('totalbase', models.PositiveBigIntegerField(default=0)),
                ('totalfactura', models.PositiveBigIntegerField(default=0)),
                ('cliente', models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.PROTECT, to='cxc.cliente')),
                ('deposito', models.ForeignKey(db_column='depositoid', on_delete=django.db.models.deletion.PROTECT, to='cxc.deposito')),
                ('moneda', models.ForeignKey(db_column='monedaid', on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda')),
                ('plazo', models.ForeignKey(db_column='plazoid', on_delete=django.db.models.deletion.PROTECT, to='cxc.plazo')),
                ('tipo_documento', models.ForeignKey(db_column='tipodocid', on_delete=django.db.models.deletion.PROTECT, to='cxc.tipodocumento')),
            ],
            options={
                'db_table': 'VENTAS',
            },
        ),
        migrations.CreateModel(
            name='CuentaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(default='VENTAS', max_length=50)),
                ('cuota', models.PositiveIntegerField()),
                ('importe', models.PositiveBigIntegerField()),
                ('cobrado', models.PositiveBigIntegerField(default=0)),
                ('vence', models.DateField()),
                ('venta', models.ForeignKey(db_column='tablaid', on_delete=django.db.models.deletion.CASCADE, to='cxc.venta')),
            ],
            options={
                'db_table': 'CUENTAS_COBRAR',
            },
        ),
    ]
