# Generated by Django 5.2.1 on 2026-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.PositiveBigIntegerField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cxc.cuentacobrar')),
            ],
            options={
                'db_table': 'COBROS',
            },
        ),
    ]
