# Generated by Django 5.2.1 on 2026-04-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('servicio', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('mail', models.CharField(blank=True, max_length=50)),
                ('ruc', models.CharField(max_length=50)),
                ('moneda', models.ForeignKey(db_column='monedaid', on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda')),
            ],
            options={
                'db_table': 'EMPRESAS',
            },
        ),
        migrations.CreateModel(
            name='PlazoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.PositiveIntegerField()),
                ('dias', models.PositiveIntegerField()),
                ('plazo', models.ForeignKey(db_column='plazoid', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cxc.plazo')),
            ],
            options={
                'db_table': 'PLAZO_DETALLES',
            },
        ),
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('codbarra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('colorid', models.PositiveIntegerField(blank=True, null=True)),
                ('tamanoid', models.PositiveIntegerField(blank=True, null=True)),
                ('disenoid', models.PositiveIntegerField(blank=True, null=True)),
                ('uxb', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('producto', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cxc.producto')),
            ],
            options={
                'db_table': 'PRODUCTO_DETALLE',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=5, max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impuesto5', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('impuesto10', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=5, max_digits=18)),
                ('producto_detalle', models.ForeignKey(db_column='codbarra', on_delete=django.db.models.deletion.PROTECT, to='cxc.productodetalle')),
                ('venta', models.ForeignKey(db_column='ventaid', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cxc.venta')),
            ],
            options={
                'db_table': 'VENTA_DETALLES',
                'unique_together': {('venta', 'producto_detalle')},
            },
        ),
    ]
