# Generated by Django 5.2.1 on 2026-06-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0003_producto_empresa_plazodetalle_productodetalle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
