# Generated by Django 5.2.1 on 2026-06-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_cliente',
        ),
    ]
