# Generated by Django 5.2.1 on 2026-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0005_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='vigente', max_length=20)),
            ],
            options={
                'db_table': 'TIMBRADOS',
            },
        ),
    ]
