# Generated by Django 5.2.1 on 2026-06-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0006_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbrado',
            name='nro_fin',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='nro_inicio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='timbrado_registro',
            field=models.ForeignKey(blank=True, db_column='timbradoid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cxc.timbrado'),
        ),
    ]
