# Generated by Django 5.2.1 on 2026-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0007_timbrado_nro_fin_timbrado_nro_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
    ]
