# Generated by Django 5.2.1 on 2026-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar'), ('PYG', 'Guaraní'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño')], default='PYG', max_length=3),
        ),
        migrations.AlterModelTable(
            name='factura',
            table='facturacion_factura',
        ),
    ]
