# Generated by Django 5.2.1 on 2026-05-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_moneda_alter_factura_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
